# .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r requirements.txt
    command: |
      export FLASK_APP=app.py
      export FLASK_ENV=development
      flask run --host=0.0.0.0 --port=5000

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter